name: demo
on:
  workflow_dispatch:
jobs:
  buildusingmaven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: build using mave
        run: mvn -B package
          
      - name: build using mave
        run: ls -lh target/
